name: Build LaTeX PDF

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up LaTeX environment
    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@v2
      with:
        # Specify the .tex file to build
        root_file: src.tex  # Change to your main .tex file name
        latexmk_use_lualatex: false
        latexmk_use_xelatex: false
        latexmk_shell_escape: false

    # Step 3: Save the generated PDF as an artifact
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-pdf
        path: main.pdf  # Ensure this matches your output PDF name
